Extractor Comparison Code
utiasASRL/radar_topometric_localization pull request #1
Opened 2024-12-19 16:53 UTC by ElliotP-K

- New Extractor tuning suite to sweep and tune extractors and their parameters 
   - To tune extractors, the user must set desired parameters (see comments in respective files) in run_parallel_test_multi_extractor.sh, parameter_search.py, detector_parameters.yaml, and external/vtr_testing_radar/src/vtr_testing_radar/config/boreas.yaml as the base config file. Execute run_parallel_test_multi_extractor.sh to sweep
   - Use graph_parameter_search.py to graph KITTI metrics across parameter sweeps on specified extractors and sequences
   - Use speed_test.py to parse the log files of odometry runs to extract the average point cloud size and runtime on specific extractors and sequences
- Added in ICP failure/skip conditions to threshold a max acceptable relative transformation (norm), and a max translational and rotational velocity difference between frames. (comment if this should be kept, removed, or added to the lidar icp odometry module aswell)
- Testing
   - Ran each extractor on a testing sequence from corresponding paper. Extractors extracted the same number of points across the entire sequence but got slightly different KITTI metrics which I believe is because I updated the STEAM version to match that of the latest version used in the [Gyro Update ](https://github.com/utiasASRL/vtr3/pull/227). I am basing this on a inspection of the log files from when the tests were ran initially to the recent ones. Performance was very similar for some extractors and at most different by ~0.3% trans error- see text file attached [test_sweep.txt](https://github.com/user-attachments/files/18200850/test_sweep.txt)
   - Ran a parameter sweep on kstrongest to confirm sweep functionality and compare metrics to those from the paper. Again different results but similar overall performance.
   - Confirmed functionality of graphing and speed test utilities

2025-01-10 16:27 UTC, lisusdaniil commented on runtime/run_eval.sh
> +# Save param file
Isn't there a concern that the param file will change between running test and evaluation? I think the config file should be copied only when launching run_test.sh?

2025-01-10 16:27 UTC, lisusdaniil commented on runtime/run_parallel_test.sh
> +# Save param file
If param file is copied in run_test.sh then is there any point of it being saved here too?

2025-01-10 16:29 UTC, lisusdaniil requested changes
I didn't check your new code in a ton of depth as it won't prevent backward compatibility.  Just a small comment about saving the config files and then good to push.

2025-01-11 15:30 UTC, ElliotP-K commented on runtime/run_parallel_test.sh
> +# Save param file
run_parallel_test.sh doesn't invoke run_test.sh or run_eval.sh so it will only be saved once depending on your script of choice.

All the run_..sh scripts call test_(odometry/localization).sh or test_(odometry/localization)_eval.sh respectively as their main function call. They are separate workflows I believe.

2025-01-11 15:32 UTC, ElliotP-K commented on runtime/run_eval.sh
> +# Save param file
Yeah that is fair, I just added it to all of them to all the files for consistency. I can remove the parameter file save from the run_eval.sh and leave it in run_test.sh and run_parallel_test.sh.

2025-01-11 16:08 UTC, merged